app:
  messages:
    welcome: Hi, Welcome to Customer Microservices!!! (staging)

spring:
  application:
    name: customer-service
  profiles:
    active: staging
  cloud:
    config:
      uri: http://localhost:9092
#      label: local, default
#      discovery:
#        enabled: true
#        service-id: config-server

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVER_HOST:localhost}:8761/eureka
  instance:
    appname: ${spring.application.name}
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    preferIpAddress: true
    nonSecurePort: ${server.port}
    metadata-map:
      startup: ${random.long}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always